loki:
  enabled: true
  isDefault: true
  persistence:
    enabled: true
    size: 10Gi
  config:
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      chunk_idle_period: 5m
      chunk_retain_period: 30s
    schema_config:
      configs:
        - from: 2020-05-15
          store: boltdb
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 168h
    storage_config:
      boltdb:
        directory: /data/loki/index
      filesystem:
        directory: /data/loki/chunks

monitoring:
  dashboards:
    enabled: true
  rules:
    enabled: true
  alerts:
    enabled: true
    annotations:
      message: '{{ $labels.job }} is failing to scrape {{ $labels.instance }}'
    labels:
      severity: critical 