apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: microservices
  labels:
    app: load-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - name: load-generator
        image: rajiniops/load-generator:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGET_SERVICE
          value: "http://service1:8000"
        - name: RPS
          value: "10"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        ports:
        - containerPort: 8080
