apiVersion: v1
kind: ServiceAccount
metadata:
  name: aiops-bot
  namespace: aiops-bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aiops-bot
  namespace: aiops-bot
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aiops-bot
  namespace: aiops-bot
subjects:
- kind: ServiceAccount
  name: aiops-bot
  namespace: aiops-bot
roleRef:
  kind: Role
  name: aiops-bot
  apiGroup: rbac.authorization.k8s.io 